autoCorrect: true
failFast: true

performance:
  SpreadOperator:
    active: false


style:
  MaxLineLength:
    maxLineLength: 120
  UnusedPrivateMember:
    active: false
  WildcardImport:
    active: false
  UnnecessaryAbstractClass:
    active: false
  ForbiddenComment:
    active: false
  ExpressionBodySyntax:
    active: false
  MagicNumber:
    active: false
  DataClassContainsFunctions:
    active: false
  MandatoryBracesIfStatements:
    active: false
  UnnecessaryApply:
    active: false

naming:
  PackageNaming:
    active: false
  FunctionMaxLength:
    active: false
  MemberNameEqualsClassName:
    active: false

comments:
  active: false

complexity:
  LabeledExpression:
    active: false
  TooManyFunctions:
    active: false
  ComplexInterface:
    active: false
  LongParameterList:
    active: false
  LargeClass:
    active: false
  ComplexMethod:
    active: false
  NestedBlockDepth:
    threshold: 10
  LongMethod:
    active: false
  ComplexCondition:
    active: false
  StringLiteralDuplication:
    active: false

potential-bugs:
  UnsafeCast:
    active: false
  LateinitUsage:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
